apiVersion : apps/v1
kind: Deployment
metadata:
  name: "clusterhomework-3915"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "clusterhomework-3915"
  template:
    metadata:
      labels:
        app: "clusterhomework-3915"
    spec:
      containers:
        - name: "clusterhomework-3915"
          image: "acrhomework.azurecr.io/clusterhomework"
          ports:
          - containerPort: 80