apiVersion : apps/v1
kind: Deployment
metadata:
  name: "clusterhomework-a965"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "clusterhomework-a965"
  template:
    metadata:
      labels:
        app: "clusterhomework-a965"
    spec:
      containers:
        - name: "clusterhomework-a965"
          image: "containerregistryfinal.azurecr.io/clusterhomework"
          ports:
          - containerPort: 80