apiVersion : apps/v1
kind: Deployment
metadata:
  name: "clusterhomework-8fa0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "clusterhomework-8fa0"
  template:
    metadata:
      labels:
        app: "clusterhomework-8fa0"
    spec:
      containers:
        - name: "clusterhomework-8fa0"
          image: "acrhomeworkfinal.azurecr.io/clusterhomework"
          ports:
          - containerPort: 80