apiVersion: v1
kind: Service
metadata:
    name: "clusterhomework-8fa0"
    labels:
        app: "clusterhomework-8fa0"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "clusterhomework-8fa0"